version: '3'
services:

  logvisualization-logparser:
      build: logparser
      image: logvisualization/logparser
      restart: always
      ports:
        - 16319:16319
      networks:
        - my-network

  logvisualization-escore:
      build: escore
      image: logvisualization/escore
      restart: always
      ports:
        - 17319:17319
      networks:
        - my-network

networks:
    my-network:
      driver: bridge