version: '3'
services:

  logvisualization-logapi:
      build: logapi
      image: logvisualization/logapi
      restart: always
      volumes:
        - /opt/log/logapi:/opt/log/logapi
      ports:
        - 16319:16319
      networks:
        - my-network

  logvisualization-escore:
      build: escore
      image: logvisualization/escore
      restart: always
      volumes:
        - /opt/log/escore:/opt/log/escore
      ports:
        - 17319:17319
      networks:
        - my-network

  logvisualization-k8sapi:
      build: k8sapi
      image: logvisualization/k8sapi
      restart: always
      volumes:
        - /opt/log/k8sapi:/opt/log/k8sapi
      ports:
        - 18319:18319
      networks:
        - my-network

  logvisualization-zipkinapi:
      build: zipkinapi
      image: logvisualization/zipkinapi
      restart: always
      volumes:
        - /opt/log/zipkinapi:/opt/log/zipkinapi
      ports:
        - 19319:19319
      networks:
        - my-network

  logvisualization-algorithm:
      build: algorithm
      image: logvisualization/algorithm
      restart: always
      ports:
        - 18888:18888
      networks:
        - my-network

networks:
    my-network:
      driver: bridge