server:
  port: 19319

spring:
  application:
    name: logvisualization-zipkinapi

es-config:
  host: 10.141.211.163
  port: 30003

es-config-133:
  host: 10.141.212.133
  port: 30003

es-config-142:
  host: 10.141.212.142
  port: 30003

logback:
  logdir: /opt/log/zipkinapi
  appname: zipkinapi