server:
  port: 18319

spring:
  application:
    name: k8sapi

k8s-cluster-config:
  masterIp: 10.141.212.23
  apiServer: https://10.141.212.23:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi12cmQ1aCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImFkN2RiODliLTE2M2YtMTFlOS1hZWY2LTAwNTA1NmE0MDJiMSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.OQkrixRWaWfmnMa1RETr03KeWPrMO_kmCX1h7ZYHml2zgggxjMvFSKXI1W6WRbHzg3Yh11yU_gBgeG8sIlmNm2ImJ65Y-xGV3ZOSuTL-bM-QRbVZS0IaJ1PscUG85UlHOuysJG5cG_ZP9ddDCdZWp4ONaJpMGxdiKFyB4WH9rg-W_93UotHCCXYrC8GUjCjIgK8kwqxMQnI8QqRyn7dpuS6gd71pN-t9IWfu4XFGeaBltJmQwbmAswl3jF__8Mp8YJ-k8cEEFQIUQpgy7L_8LhT2NlOPMfzNehTEeZxLEft50QrWOt1Gbv-Oh4ss9ZvQ6ktPp7PSw8AIl8L5FHeLSg

logback:
  logdir: /opt/log/k8sapi
  appname: k8sapi