server:
  port: 18319

spring:
  application:
    name: k8sapi

k8s-cluster-config:
  masterIp: 10.141.211.163
  apiServer: https://10.141.211.163:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi0ycmxtNSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjI2OWU1YTk2LWE1MzktMTFlOC1hZjQxLTAwNTA1NmE0OGJmNCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.PimMZ4Zy8NeC2WXVqegd9CCRiS58fkQcQNaRf2U1Jcz6ing_wSa0VbBms05M83Tyy5UbLMkRv4eD0pGAqvXs24HidWtuqPgdfobOyutfO41P4Dy6kcJPsBr0iqWHgSvweDSBs-2F1JQneXBYOJUZKLCgk7gL6mIA_Nua2G1lRuf1MgKSG1ZqgkK-De0dDLWNUsW-N10FqRSK9Z2sHHZwpa4JHj_3N63QQaZqkqaX8BxVTN7dJ8I0l5Ng4koGMVDyZMBwqeDSEa4kClbgBiIl3Do8eFsuPApUvQ1GwjiDtsQLLDK9dz9ng9idxwCrvtQcV1ir9F_s7Rb5fRLEY_2PFw

k8s-cluster-config-136:
  masterIp: 10.141.212.136
  apiServer: https://10.141.212.136:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi1nZ2RoeCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImE0NWZhMGE3LWExNGQtMTFlOC1hMDhmLTAwNTA1NmE0OWYzMCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.MxGTuKG01kT1ew3zJLsyI87Y6hENBpSBsqyI7QwQTthPNXA2jiV5dzNF8Sy7EhUS5sXqbe9MdlQGfi8tiPMn2f4TyMI47YaUe4xq2LjeQJP0Vh6MjI5XPL8H7OyxoU6ggV7v4O3AYqb2mNzDGzNWIm757n0JxIzcEkpsJuHYH9FyZyw1B2E6Bs-syfLi_uVeYFyJcb_JxTq4lEh0BS_hqkJTYpJdQAVujOBnZCpeTB7WNHd4W4D2snqCEKAzu23AZK-XZGfaF7s086-X-2FzsZFEB37h9fL1zcZ3upi_Y374UoD5qaRd2PwrgdCUaV9f7ACEHXKzYcdj5bDPPUZKXw

k8s-cluster-config-142:
  masterIp: 10.141.212.142
  apiServer: https://10.141.212.142:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi1zZHY4OCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjlhMzM5NzI1LWE0M2YtMTFlOC1iZGJmLTAwNTA1NmE0MDg0MCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.FxoNIIrlVvn0EV5HqTwQh--QO-gL-MTEz6BXvY9hsXEUSe-HuWgwb4cokPGAxEavPLafrbEK8YiL66fT3C-xH0T43my4HN_njJEWMwmBBiFU-G5B5QwMbP7WTSXTtrpkeyQM0G8wysWFhsUsper5Ke-xX8I0eY3CBOxeMchsO7QAd-py13h_ufXVKoPZvz5wAjF_5sLMRiJfpG5FKjOTe9OgCLNCr7yCrHMvcr-TvMVcfja3Eyv3lOJIjes2jpCOwXH8xRJ-dRS0CpPfiXgYDDqgwK3SjTQ7fTOIQgZNBsmRNYmcCPWKQvuQMOlVGwf1ozlaOZmyGggvirSWKJUOlA

logback:
  logdir: /opt/log/k8sapi
  appname: k8sapi