server:
  port: 18319

spring:
  application:
    name: k8sapi

k8s-cluster-config:
  masterIp: 10.141.211.163
  apiServer: https://10.141.211.163:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi12cTlkZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImE3NzI0YzM0LTY1NjYtMTFlOC1hMjI2LTAwNTA1NmE0OGJmNCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.juLf7F-OOfSfYvEeoeJEJqPJ14-8u5moK9R8yFh-6909WFiU4ClQ7e3fiB35fyJnb4umyez-btVzEfa6D23BTSD_p57O16a0AC3KRyC2ccbWZkp9PovFEb_2KOkNk3tUe71gL5uqY4xfQFLVgFxr1u07fsf1i_jwb6q4E9nsT4axLDyvMGxMSifqJwDDfZ6r2WaH9gAeQepiBYTKxQJoqVQgxUb1QODQtUKVL1kikVRR8s63X5kYdCCHCQnxmx3KBZZTTBinKeRAFtja6NNwddLai_HB3PDIaK0UrRnHKtH3gPK9ee1HZE_TObvgB1H30MSd8e6-059zdVetMC8NdA
