server:
  port: 18319

spring:
  application:
    name: k8sapi

k8s-cluster-config:
  masterIp: 10.141.211.163
  apiServer: https://10.141.211.163:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi0ycmxtNSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjI2OWU1YTk2LWE1MzktMTFlOC1hZjQxLTAwNTA1NmE0OGJmNCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.PimMZ4Zy8NeC2WXVqegd9CCRiS58fkQcQNaRf2U1Jcz6ing_wSa0VbBms05M83Tyy5UbLMkRv4eD0pGAqvXs24HidWtuqPgdfobOyutfO41P4Dy6kcJPsBr0iqWHgSvweDSBs-2F1JQneXBYOJUZKLCgk7gL6mIA_Nua2G1lRuf1MgKSG1ZqgkK-De0dDLWNUsW-N10FqRSK9Z2sHHZwpa4JHj_3N63QQaZqkqaX8BxVTN7dJ8I0l5Ng4koGMVDyZMBwqeDSEa4kClbgBiIl3Do8eFsuPApUvQ1GwjiDtsQLLDK9dz9ng9idxwCrvtQcV1ir9F_s7Rb5fRLEY_2PFw

k8s-cluster-config-133:
  masterIp: 10.141.212.133
  apiServer: https://10.141.212.133:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi1xYzd4YiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjYwZWQxYWVmLWE3NzgtMTFlOC1hZGFhLTAwNTA1NmE0YjRiZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.OdnXHKvJtyiZkKvGVTExWrJoOZykpXjCfTufFF12u_kAjxEDvHfe--nMXyazkPBG0bSfwh-T52JL3OQOd_Eg3Ry7-KT_VkjtioyPYqkDbuZE15jimkvf2bRCwHUb_1A--47GEt4uCslvKWbVS_1fyKGvPY2E1Nw7jh_DJIvWh1gQ-X22m_Y8Tw_n0Ok31L25eSHtCTgpOvotdYwkB0FzSlqZeWBWBhMrh_vsPDQVKNpAjeSbx25g1XvMSqdIzK9pFJo_5_6eb-vnmhaYiwn-E-OeNLF3YF7jCjtGdSN-p2MhXCBvi6unhDDVkmV-PJQOjo2mT1tIzYnEUntgQnJmfw

k8s-cluster-config-142:
  masterIp: 10.141.212.142
  apiServer: https://10.141.212.142:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi1zZHY4OCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjlhMzM5NzI1LWE0M2YtMTFlOC1iZGJmLTAwNTA1NmE0MDg0MCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.FxoNIIrlVvn0EV5HqTwQh--QO-gL-MTEz6BXvY9hsXEUSe-HuWgwb4cokPGAxEavPLafrbEK8YiL66fT3C-xH0T43my4HN_njJEWMwmBBiFU-G5B5QwMbP7WTSXTtrpkeyQM0G8wysWFhsUsper5Ke-xX8I0eY3CBOxeMchsO7QAd-py13h_ufXVKoPZvz5wAjF_5sLMRiJfpG5FKjOTe9OgCLNCr7yCrHMvcr-TvMVcfja3Eyv3lOJIjes2jpCOwXH8xRJ-dRS0CpPfiXgYDDqgwK3SjTQ7fTOIQgZNBsmRNYmcCPWKQvuQMOlVGwf1ozlaOZmyGggvirSWKJUOlA

logback:
  logdir: /opt/log/k8sapi
  appname: k8sapi