server:
  port: 18319

spring:
  application:
    name: k8sapi

k8s-cluster-config:
  masterIp: 10.141.211.163
  apiServer: https://10.141.211.163:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi1tZmtqOCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImNlMThlNTFhLTg2OGQtMTFlOC04NTg3LTAwNTA1NmE0OGJmNCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.esJgpZxetp5I0wC2azyIq9JgjzTdnSmPdAZw9mLTcH4wk63YThQvvvMW8ocP6mBbbJ6YpI-6Gubok_o4bHFa8kQIdL88B3qxHjWCsKriWKZQcfkMKk8HDGFfdF6Eg8S7UMFeyqeIwq-hFplkyEiCuPZ9pL_P7ZlsAhwFXsufAzXtL9LSx7cBigYhPTharZcw_nCUHBN5LODQy23qRny1WSRQ9-536mnGIYqNXx4yktEQ1nywJol8S1FCHZH_Wyw7bEZU2FknMkVzVQErp4pBuAEqhw-8uARLZl3wTptQ1EVzXmv2OtMiFdIRSm1XMOoQpGwl4V1746-fEnOPckxuHg